name: Bashar-RDP-Final-Fix
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Installing Tailscale
        run: |
          curl -L https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -o tailscale-setup.exe
          start-process -FilePath .\tailscale-setup.exe -ArgumentList "/quiet" -Wait
          
      - name: Connecting to Tailscale
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey=tskey-auth-kW3Fivz9UE11CNTRL-Cev23vi5jufkfKyX9Sniuf1QxCD7GZTn3
          
      - name: Setting Up Remote Desktop
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          
      - name: Reset Administrator Password
        run: |
          net user administrator BasharHacker2026Admin!
          
      - name: Keep Alive (6 Hours)
        run: |
          Write-Host "RDP is Ready! Connect using Tailscale IP."
          sleep 21600
